
INSERT INTO AUTHOR(AUTHOR_ID, FIRST_NAME, LAST_NAME)
    VALUES
    (     NULL, 'Craig','Wells'    ),
    (     NULL, 'Joshua','Bloch'   ),
    (     NULL, 'Alex','Antonov'   ),
    (     NULL, 'Joyce','Farrell'  ),
    (     NULL, 'Cay','Horstmann'  ), 
    (     NULL, 'Janet','Gregory'  ), 
    (     NULL, 'Greg','Turnquist' ),
    (     NULL, 'Walter','Savich'  ),
    (     NULL, 'John','Carnell'   ),
    (     NULL, 'Zed','Shaw'       ),
    (     NULL, 'Wes','McKinney'   ),
    (     NULL, 'Paul','Barry'     ),
    (     NULL, 'Mark','Luiz'      ),
    (     NULL, 'Douglas','Crockford'),
    (     NULL, 'Kyle','Simpson'),
    (     NULL, 'Bear','Bibeault'),
    (     NULL, 'Svetlana','Isakova'),
    (     NULL, 'Antonio','Leiva'),
    (     NULL, 'Stephen','Samuel');

INSERT INTO BOOK (BOOK_ID, BOOK_TITLE, BOOK_YEAR, AUTHOR_ID)
VALUES 
    (NULL, 'Spring Boot in Action', 2018, 42.45, (SELECT Author_ID from author where last_name = 'Wells')),
    (NULL, 'Core Java for the Impatient', 2018, 52.33, (SELECT Author_ID from author where last_name = 'Horstmann')),
    (NULL, 'Spring Microservices in Action', 2016, 23.43, (SELECT Author_ID from author where last_name = 'Carnell')),
    (NULL, 'Java Programming', 2018, 23.00, (SELECT Author_ID from author where last_name = 'Farrell')),
    (NULL, 'Beginning Java Databases', 2001, 45.67, (SELECT Author_ID from author where last_name = 'Carnell')),
    (NULL, 'Effective Java', 2017, 89.32, (SELECT Author_ID from author where last_name = 'Bloch')),
    (NULL, 'Spring Boot 2.0', 2017, 101.23,(SELECT Author_ID from author where last_name = 'Antonov')),
    (NULL, 'Spring Boot Cookbook', 2015, 75.16, (SELECT Author_ID from author where last_name = 'Antonov')),
    (NULL, 'Learning spring Boot 2.0', '2017', 30.0, (SELECT Author_ID from author where last_name = 'Turnquist')),
    (NULL, 'Absolute Java', '2015',54.6, (SELECT Author_ID from author where last_name = 'Savich')),
    (NULL, 'Agile Testing', '2015',33.33, (SELECT Author_ID from author where last_name = 'Gregory')),
    (NULL, 'Java: An Introduction to Problem Solving', '2017', 76.99, (SELECT Author_ID from author where last_name = 'Savich')),
    (NULL, 'Learn Python the Hard Way', 2013, 17.27, (SELECT Author_ID from author where last_name = 'Shaw')),
    (NULL, 'Python for Data Analysis', 2011, 54.39 , (SELECT Author_ID from author where last_name = 'McKinney')),
    (NULL, 'Head First Python', 2010, 50.12 , (SELECT Author_ID from author where last_name = 'Barry')),
    (NULL, 'Programming Python', 1996,67.99 , (SELECT Author_ID from author where last_name = 'Luiz')),
    (NULL, 'JavaScript: The Good Parts', 2008, 21.59, (SELECT Author_ID from author where last_name = 'Crockford')),
    (NULL, "You Don't Know JS:Scope & Closures", 2014,32.95 , (SELECT Author_ID from author where last_name = 'Simpson')),
    (NULL, 'Secrets of the JavaScript Ninja', 2008, 41.99, (SELECT Author_ID from author where last_name = 'Bibeault')),
    (NULL, 'Kotlin in Action', 2017, 41.99, (SELECT Author_ID from author where last_name = 'Isakova')),
    (NULL, 'Kotlin for Android Developers', 2016, 43.66, (SELECT Author_ID from author where last_name = 'Leiva')),
    (NULL, 'Programming Kotlin', 2017, 45.99 , (SELECT Author_ID from author where last_name = 'Samuel'));
